name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Default registry = GHCR. To use Docker Hub, set: REGISTRY=docker.io and login below.
  REGISTRY: ghcr.io
  # Image names (change if you like)
  BACKEND_IMAGE: rental-api
  FRONTEND_IMAGE: rental-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed if you push to GHCR
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            image: ${{ env.BACKEND_IMAGE }}
            context: ./backend
            file: ./backend/Dockerfile
          - name: frontend
            image: ${{ env.FRONTEND_IMAGE }}
            context: ./frontend
            file: ./frontend/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch, optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 👉 If pushing to GHCR (recommended): login using GITHUB_TOKEN
      - name: Login to GHCR
        uses: docker/login-action@v3
        if: env.REGISTRY == 'ghcr.io'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 👉 If pushing to Docker Hub instead, comment the GHCR login above,
      #     create secrets DOCKERHUB_USERNAME and DOCKERHUB_TOKEN, and use:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image }}
          tags: |
            type=sha
            type=raw,value=${{ github.run_number }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build (and optionally push) ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}  # push only on main
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
